name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build cmd/server/main.go
  test:
    name: Test
    steps:
      - name: Test
        run: go test $(go list ./...)
